############################################################################
# 原則 http://jekyllrb.com/docs/configuration/#default-configuration からの
# 差分のみ記述している。記述順序も前述に従う。

### Handling Reading
exclude:
  - 'scripts'
  - 'Gemfile'
  - 'README.md'
  - 'vendor'
encoding: utf-8

### Filtering Content
future: true

### Plugins
gems:
  - jemoji
  - jekyll-sitemap

### Outputting
# default と同じだが、万が一デフォルトが変わってしまうと記事のURLが変わってしま
# いクリティカルなので、明示的に指定した。
permalink: date

### Markdown Processors
kramdown:
  input: GFM

############################################################################
# 以下はvim-jp固有の設定項目

# baseurl と紛らわしいが別物なので要注意
base-url: http://vim-jp.org

hotkeys: true
