encoding: utf-8
safe:        false
base-url:    http://vim-jp.org

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter: pygments
markdown:    redcarpet
permalink:   date

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "superscript"]
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

exclude:
  - 'scripts'
  - 'Gemfile'
  - 'README.md'
  - 'vendor'

gems:
  - jemoji
  - jekyll-sitemap

hotkeys: true
